// SZTU-Directory/src/components/Search.vue
<template>
    <div class="searchbox-bg">
        <div class="searchbox">
            <input 
                type="text"  
                class="search-input"
                placeholder='请输入姓名、工号、部门、电话搜索'
                v-model="inputValue"
                @keydown.enter="handleSearch"
            />
            <button class="searchButton" @click="handleSearch">
                <img :src="logo" alt="搜索" />
            </button>
        </div>
    </div>
</template>

<script lang="ts" setup>
    import logo from '@/assets/search.png';
    import useTeacherList from '@/hooks/useTeacherList';
    import {ref} from 'vue';

    const {GetSearchTeacherList} = useTeacherList();

    const inputValue = ref<string>("");

    const handleSearch = ():void => {
        GetSearchTeacherList(inputValue.value);

        inputValue.value = "";
    }


</script>

<style scoped>
    .searchbox-bg {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
        height: 230px;
        background-color: #1d2e6e;
    }

    .searchbox {
        display: flex;
        width: 600px;
        height: 50px;
    }

    .searchbox .search-input {
        height: 50px;
        width: 530px;
        border-radius: 50px 0 0 50px;
        border: none;
        line-height: 50px;
        background-color: #fff;
        padding-left: 20px;
        font-size: 18px;
        outline: none;
    }

    .searchButton {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 50px;
        width: 50px;
        border-radius: 0 50px 50px 0;
        border: none;
        background-color: #fff;
    }

    .searchButton img{
        width: 30px;
        height: 30px;
    }
</style>

// dbwork/src/Components/Search/index.jsx
import React from 'react'
import axios from 'axios';
import {useRef} from 'react';

import './index.css';
import logo from '../../assets/search.png';

export default function Search(props) {

  const {setTeacherData,setPageNum} = props;

  const inputRef = useRef(null);

  const handleSearch = () => {
    if (inputRef.current.value !== ""){
      const searchValue = inputRef.current.value;

      const fetchSearch = async () => {
        try {
          const response = await axios.get(`/index/${searchValue}`)
          setTeacherData(response.data);
          setPageNum(1);
          console.log(response.data);
          
          inputRef.current.value = "";
        }
        catch(error){
          inputRef.current.value = "";
          alert('Error fetching data:', error);
        }
      }

      fetchSearch();
    }
  }

  return (
    <div className="searchbox-bg">
        <div className="searchbox">
            <input 
                ref={inputRef}
                type="text"  
                className="input"
                onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                placeholder='请输入姓名、工号、部门、电话搜索'
            />
            <button className="searchButton" onClick={handleSearch}>
                <img src={logo} alt="搜索" />
            </button>
        </div>
    </div>
  )
}
