// dbwork/src/Components/DataItems/index.jsx
import React from 'react'

import './index.css';

export default function DataItems(props) {

  const {teacherItem} = props;
    
  return (
    <div className="dataItems">
        <div className="name-item">
          {
            teacherItem.name != null ? teacherItem.name : ""
          }
        </div>
        <div className="sno-item">
          {
            teacherItem.sno != null ? teacherItem.sno : ""
          }
        </div>
        <div className="inline-item">
          {
            teacherItem.inline != null ? teacherItem.inline : ""
          }
        </div>
        <div className="outline-item">
          {
            teacherItem.outline != null ? teacherItem.outline : ""
          }
        </div>
        <div className="department-item">
          {
            teacherItem.department != null ? teacherItem.department : ""
          }
        </div>
        <div className="department-sno-item">
          {
            teacherItem.department_sno != null ? teacherItem.department_sno : ""
          }
        </div>
        <div className="email-item">
          {
            teacherItem.email != null ? teacherItem.email : ""
          }
        </div>
        <div className="address-item">
          {
            teacherItem.address != null ? teacherItem.address : ""
          }
        </div>
    </div>
  )
}

// SZTU-Directory/src/components/DataItems.vue
<template>
    <div class="dataItems">
        <div class="name-item">
            {{ props.item.name }}
        </div>
        <div class="sno-item">
            {{ props.item.sno }}
        </div>
        <div class="inline-item">
            {{ props.item.inline }}
        </div>
        <div class="outline-item">
            {{ props.item.outline }}
        </div>
        <div class="department-item">
            {{ props.item.department }}
        </div>
        <div class="department-sno-item">
            {{ props.item.department_sno }}
        </div>
        <div class="email-item">
            {{ props.item.email }}
        </div>
        <div class="address-item">
            {{ props.item.address }}
        </div>
    </div>
</template>

<script lang="ts" setup>
    import { type TeacherInter } from '@/types';
    import { type PropType } from 'vue';

    const props = defineProps({
        item: {
            type: Object as PropType<TeacherInter>,
            required: true,
        }
    })
</script>

<style>
    .dataItems {
        display: flex;
        height: 72px;
        width: 100%;
        /* background-color: pink; */
        border-top: 0.5px solid #e2e2e2;
    }

    .name-item {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 12.5%;
        height: 100%;
        font-size: 15px;
        font-weight: 400;
        color: #3d3d3d;
    }

    .sno-item {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 12.5%;
        height: 100%;
        font-size: 15px;
        font-weight: 400;
        color: #3d3d3d;
    }

    .inline-item {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 12.5%;
        height: 100%;
        font-size: 15px;
        font-weight: 400;
        color: #3d3d3d;
    }

    .outline-item {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 12.5%;
        height: 100%;
        font-size: 15px;
        font-weight: 400;
        color: #3d3d3d;
    }

    .department-item{
        display: flex;
        align-items: center;
        justify-content: center;
        width: 12.5%;
        height: 100%;
        font-size: 15px;
        font-weight: 400;
        color: #3d3d3d;
    }

    .department-sno-item {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 12.5%;
        height: 100%;
        font-size: 15px;
        font-weight: 400;
        color: #3d3d3d;
    }

    .email-item {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 12.5%;
        height: 100%;
        font-size: 15px;
        font-weight: 400;
        color: #3d3d3d;
    }

    .address-item {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 12.5%;
        height: 100%;
        font-size: 15px;
        font-weight: 400;
        color: #3d3d3d;
    }
</style>
