// dbwork/src/Components/Footer/index.jsx
import React from 'react'

import './index.css';

import logo from '../../assets/down_small.png'

export default function Footer(props) {

  const {teacherData,pageNum,setPageNum} = props;

  //计算总页数
  const allPages = Array.isArray(teacherData) ? Math.ceil(teacherData.length / 10) : 0; 
  //计算当前页面数组
  let showPages = [];
  if (allPages >= 10 && pageNum >=5 && pageNum <= allPages-4) {
    for(let i = pageNum-4;i<=pageNum+5;i++){
        showPages.push(i);
    }
  }else if(allPages >= 10 && pageNum < 5){
    for(let i = 1;i<=10;i++){
        showPages.push(i);
    }
  }else if(allPages >= 10 && pageNum > allPages-4){
    for(let i = allPages-9;i<=allPages;i++){
        showPages.push(i);
    }
  }else{
    for(let i = 1 ; i <= allPages ; i++){
        showPages.push(i);
    }
  }

  const handleChangePage = (e) => {
    setPageNum(e);
  }

  const handleBack = () => {
    if (pageNum > 1){
        setPageNum(pageNum-1);
    }
  }

  const handleUp = () => {
    if (pageNum < allPages){
        setPageNum(pageNum+1);
    }
  }

  return (
    <div className="footer">
        <div className="footer-select">
            {/* 控制页数三个板块 */}
            <div className='up-back-jump'>
                <div className="footer-back" onClick={handleBack}>
                  <img src={logo} alt="" />
                </div>
                {
                    showPages.map((e) => {
                        return <div key={e} className={`footer-page ${pageNum === e ? "active" : ""}`} onClick={() => handleChangePage(e)}>{e}</div>
                    })
                }
                <div className="footer-up" onClick={handleUp}>
                  <img src={logo} alt="" />
                </div>
            </div>
            <p className='howManyPages'>
              {pageNum}/{allPages}
            </p>
        </div>
    </div>
  )
}

// SZTU-Directory/src/components/Footer.vue
<template>
    <div class="footer">
        <div class="footer-select">
            <div class='up-back-jump'>
                <div class="footer-back" @click="handleBack">
                  <img :src="logo" alt="" />
                </div>
                <div
                    v-for="page in pageList"
                    :key="page"
                    :class="['footer-page', { active: page === pageNum }]"
                    @click="setPageNum(page)"
                >
                {{ page }}
                </div>
                <div class="footer-up" @click="handleUp">
                  <img :src="logo" alt="" />
                </div>
            </div>
            <p class='howManyPages'>
                {{ pageNum }}/{{ allPageNum }}
            </p>
        </div>
    </div>
</template>

<script lang="ts" setup>
    import logo from '@/assets/down_small.png';
    import useTeacherList from '@/hooks/useTeacherList';
    import {computed} from 'vue';

    const {pageNum,allPageNum,setPageNum} = useTeacherList();

    const handleBack = ():void => {
        if(pageNum.value > 1){
            setPageNum(pageNum.value - 1);
        }
    }

    const handleUp = ():void => {
        if(pageNum.value < allPageNum.value){
            setPageNum(pageNum.value + 1);
        }
    }

    const pageList = computed(() => {
        let pageList = [];

        if (allPageNum.value >=10 && pageNum.value >=5 && pageNum.value <= allPageNum.value-4){
            for(let i = pageNum.value-4;i<=pageNum.value+5;i++){
                pageList.push(i);
            }
        }else if(allPageNum.value >= 10 && pageNum.value < 5){
            for(let i=1; i<=10; i++){
                pageList.push(i);
            }
        }else if(allPageNum.value >= 10 && pageNum.value > allPageNum.value-4){
            for(let i=allPageNum.value-9;i<=allPageNum.value;i++){
                pageList.push(i);
            }
        }else{
            for(let i=1;i<=allPageNum.value;i++){
                pageList.push(i);
            }
        }

        return pageList;
    })
</script>

<style>
    .footer {
        display: flex;
        justify-content: end;
        height: 80px;
        width: 100%;
        /* background-color: pink; */
    }

    .footer-select {
        display: flex;
        align-items: center;
        justify-content: center;
        margin-right: 30%;
        width: 35%;
        height: 100%;
        background-color: #fff;
        flex-direction: column;
    }

    .up-back-jump {
        display: flex;
        width: 65%;
        height: 40px;
        justify-content: center;
    }

    .footer-back {
        text-align: center;
        line-height: 22px;
        width: 22px;
        height: 22px;
        background-color: #e5e2e2;
    }

    .footer-back img {
        width: 14px;
        height: 14px;
        transform: rotate(90deg);
    }

    .footer-up {
        text-align: center;
        line-height: 22px;
        width: 22px;
        height: 22px;
        background-color: #e5e2e2;
    }

    .footer-up img {
        width: 14px;
        height: 14px;
        transform: rotate(-90deg);
    }

    .footer-page {
        width: 22px;
        height: 22px;
        text-align: center;
        line-height: 22px;
        background-color: #f7f4f4;
    }

    .footer-page.active {
        background-color: #3832e7aa;
    }

    .footer-page:hover{
        background-color: #110f4e56;
        color: white;
        cursor: pointer;
    }

    .howManyPages {
        /* background-color: #e5e2e2; */
        color: #706f6f;
    }
</style>
